/*

AUTOGENERATED KERNEL
Settings:
 LMUL=1
 M=16
 M_tail_scalar_from=2
 N=8
 __riscv_='__riscv_'
 complex=False
 conjugate=False
 cpu='zvl256b'
 force_acc_double=False
 index_type='BLASLONG'
 op='gemm'
 param_precision='float'
 reg_width_bits=256
 tail_policy=''
 trace=False

Derived:
 ELEN_ACC=32
 ELEN_PARAM=32
 LMUL_ACC=1
 VFMACC='__riscv_vfmacc_vf_f32m1'
 VFMUL='__riscv_vfmul_vf_f32m1'
 VLEV='__riscv_vle32_v_f32m1'
 VLSEV='__riscv_vlse32_v_f32m1'
 VMACC_TO_ACC='__riscv_vfmacc_vf_f32m1'
 VMUL_TO_ACC='__riscv_vfmul_vf_f32m1'
 VSETVL='__riscv_vsetvl_e32m1'
 VSEV='__riscv_vse32_v_f32m1'
 VSSEV='__riscv_vsse32_v_f32m1'
 acc_vector_t='vfloat32m1_t'
 output='sgemm_kernel_16x8_zvl256b.c'
 param_scalar_t='float'
 param_vector_t='vfloat32m1_t'

*/

#include "common.h"

//#define GEMM_RIGHT_EDGE    // One pass for right edge - unpacking A
//#define GEMM_BOTTOM_EDGE   // One pass for bottom edge - unrolling K
//#define USE_LMUL2          // Less operations and pointers - but slower (compiler issue)

#ifdef GEMM_RIGHT_EDGE
//#define GEMM_NEW_PACKING   // Right edge packed data friendly

#define FORCEINLINE      inline __attribute__((always_inline))

#ifdef GEMM_NEW_PACKING
static void FORCEINLINE M_TAIL_ONE(BLASLONG K, const BLASLONG M, const BLASLONG N, const BLASLONG S, FLOAT alpha, FLOAT* A0, FLOAT*, FLOAT*, FLOAT*, FLOAT* B, FLOAT* C, BLASLONG ldc)
#else
static void FORCEINLINE M_TAIL_ONE(BLASLONG K, const BLASLONG M, const BLASLONG N, const BLASLONG S, FLOAT alpha, FLOAT* A0, FLOAT* A1, FLOAT* A2, FLOAT* A3, FLOAT* B, FLOAT* C, BLASLONG ldc)
#endif
{
    if (N >= 4) {
        vfloat32m1_t B0 = __riscv_vle32_v_f32m1(B, N);
        B += N;

        vfloat32m1_t result0, result1, result2, result3, result4, result5, result6, result7;
        vfloat32m1_t result8, result9, resultA, resultB, resultC, resultD, resultE;
        if (M & 8) {
            result0 = __riscv_vfmul_vf_f32m1(B0, A0[0], N);
            result1 = __riscv_vfmul_vf_f32m1(B0, A0[1], N);
            result2 = __riscv_vfmul_vf_f32m1(B0, A0[2], N);
            result3 = __riscv_vfmul_vf_f32m1(B0, A0[3], N);
            result4 = __riscv_vfmul_vf_f32m1(B0, A0[4], N);
            result5 = __riscv_vfmul_vf_f32m1(B0, A0[5], N);
            result6 = __riscv_vfmul_vf_f32m1(B0, A0[6], N);
            result7 = __riscv_vfmul_vf_f32m1(B0, A0[7], N);
#ifndef GEMM_NEW_PACKING
            A0 += 8;
#endif
        }
#ifdef GEMM_NEW_PACKING
        if (M & 4) {
            result8 = __riscv_vfmul_vf_f32m1(B0, A0[0 + (M & 0x8)], N);
            result9 = __riscv_vfmul_vf_f32m1(B0, A0[1 + (M & 0x8)], N);
            resultA = __riscv_vfmul_vf_f32m1(B0, A0[2 + (M & 0x8)], N);
            resultB = __riscv_vfmul_vf_f32m1(B0, A0[3 + (M & 0x8)], N);
        }
        if (M & 2) {
            resultC = __riscv_vfmul_vf_f32m1(B0, A0[0 + (M & 0xC)], N);
            resultD = __riscv_vfmul_vf_f32m1(B0, A0[1 + (M & 0xC)], N);
        }
        if (M & 1) {
            resultE = __riscv_vfmul_vf_f32m1(B0, A0[0 + (M & 0xE)], N);
        }
        A0 += M;
#else
        if (M & 4) {
            result8 = __riscv_vfmul_vf_f32m1(B0, A1[0], N);
            result9 = __riscv_vfmul_vf_f32m1(B0, A1[1], N);
            resultA = __riscv_vfmul_vf_f32m1(B0, A1[2], N);
            resultB = __riscv_vfmul_vf_f32m1(B0, A1[3], N);
            A1 += 4;
        }
        if (M & 2) {
            resultC = __riscv_vfmul_vf_f32m1(B0, A2[0], N);
            resultD = __riscv_vfmul_vf_f32m1(B0, A2[1], N);
            A2 += 2;
        }
        if (M & 1) {
            resultE = __riscv_vfmul_vf_f32m1(B0, A3[0], N);
            A3 += 1;
        }
#endif

        for (BLASLONG k = 1; k < K; k++) {
            B0 = __riscv_vle32_v_f32m1(B, N);
            B += N;

            if (M & 8) {
                result0 = __riscv_vfmacc_vf_f32m1(result0, A0[0], B0, N);
                result1 = __riscv_vfmacc_vf_f32m1(result1, A0[1], B0, N);
                result2 = __riscv_vfmacc_vf_f32m1(result2, A0[2], B0, N);
                result3 = __riscv_vfmacc_vf_f32m1(result3, A0[3], B0, N);
                result4 = __riscv_vfmacc_vf_f32m1(result4, A0[4], B0, N);
                result5 = __riscv_vfmacc_vf_f32m1(result5, A0[5], B0, N);
                result6 = __riscv_vfmacc_vf_f32m1(result6, A0[6], B0, N);
                result7 = __riscv_vfmacc_vf_f32m1(result7, A0[7], B0, N);
#ifndef GEMM_NEW_PACKING
                A0 += 8;
#endif
            }
#ifdef GEMM_NEW_PACKING
            if (M & 4) {
                result8 = __riscv_vfmacc_vf_f32m1(result8, A0[0 + (M & 0x8)], B0, N);
                result9 = __riscv_vfmacc_vf_f32m1(result9, A0[1 + (M & 0x8)], B0, N);
                resultA = __riscv_vfmacc_vf_f32m1(resultA, A0[2 + (M & 0x8)], B0, N);
                resultB = __riscv_vfmacc_vf_f32m1(resultB, A0[3 + (M & 0x8)], B0, N);
            }
            if (M & 2) {
                resultC = __riscv_vfmacc_vf_f32m1(resultC, A0[0 + (M & 0xC)], B0, N);
                resultD = __riscv_vfmacc_vf_f32m1(resultD, A0[1 + (M & 0xC)], B0, N);
            }
            if (M & 1) {
                resultE = __riscv_vfmacc_vf_f32m1(resultE, A0[0 + (M & 0xE)], B0, N);
            }
            A0 += M;
#else
            if (M & 4) {
                result8 = __riscv_vfmacc_vf_f32m1(result8, A1[0], B0, N);
                result9 = __riscv_vfmacc_vf_f32m1(result9, A1[1], B0, N);
                resultA = __riscv_vfmacc_vf_f32m1(resultA, A1[2], B0, N);
                resultB = __riscv_vfmacc_vf_f32m1(resultB, A1[3], B0, N);
                A1 += 4;
            }
            if (M & 2) {
                resultC = __riscv_vfmacc_vf_f32m1(resultC, A2[0], B0, N);
                resultD = __riscv_vfmacc_vf_f32m1(resultD, A2[1], B0, N);
                A2 += 2;
            }
            if (M & 1) {
                resultE = __riscv_vfmacc_vf_f32m1(resultE, A3[0], B0, N);
                A3 += 1;
            }
#endif
        }

        vfloat32m1_t c8, c9, cA, cB, cC, cD, cE, cF;
        if (M & 8) {
            vfloat32m1x8_t c18;
            if (S) {
                c18 = __riscv_vlseg8e32_v_f32m1x8(C, N);
            } else {
                c18 = __riscv_vlsseg8e32_v_f32m1x8(C, ldc * sizeof(float), N);
            }
            c8 = __riscv_vfmacc_vf_f32m1(__riscv_vget_v_f32m1x8_f32m1(c18, 0), alpha, result0, N);
            c9 = __riscv_vfmacc_vf_f32m1(__riscv_vget_v_f32m1x8_f32m1(c18, 1), alpha, result1, N);
            cA = __riscv_vfmacc_vf_f32m1(__riscv_vget_v_f32m1x8_f32m1(c18, 2), alpha, result2, N);
            cB = __riscv_vfmacc_vf_f32m1(__riscv_vget_v_f32m1x8_f32m1(c18, 3), alpha, result3, N);
            cC = __riscv_vfmacc_vf_f32m1(__riscv_vget_v_f32m1x8_f32m1(c18, 4), alpha, result4, N);
            cD = __riscv_vfmacc_vf_f32m1(__riscv_vget_v_f32m1x8_f32m1(c18, 5), alpha, result5, N);
            cE = __riscv_vfmacc_vf_f32m1(__riscv_vget_v_f32m1x8_f32m1(c18, 6), alpha, result6, N);
            cF = __riscv_vfmacc_vf_f32m1(__riscv_vget_v_f32m1x8_f32m1(c18, 7), alpha, result7, N);
            c18 = __riscv_vcreate_v_f32m1x8(c8, c9, cA, cB, cC, cD, cE, cF);
            if (S) {
                __riscv_vsseg8e32_v_f32m1x8(C, c18, N);
            } else {
                __riscv_vssseg8e32_v_f32m1x8(C, ldc * sizeof(float), c18, N);
            }
        }
        if ((M & 7) == 1) {
            if (S) {
                cE = __riscv_vle32_v_f32m1(C + (M & 8), N);
            } else {
                cE = __riscv_vlse32_v_f32m1(C + (M & 8), ldc * sizeof(float), N);
            }
        } else if ((M & 7) == 2) {
            vfloat32m1x2_t c12;
            if (S) {
                c12 = __riscv_vlseg2e32_v_f32m1x2(C + (M & 8), N);
            } else {
                c12 = __riscv_vlsseg2e32_v_f32m1x2(C + (M & 8), ldc * sizeof(float), N);
            }
            cC = __riscv_vget_v_f32m1x2_f32m1(c12, 0);
            cD = __riscv_vget_v_f32m1x2_f32m1(c12, 1);
        } else if ((M & 7) == 3) {
            vfloat32m1x3_t c13;
            if (S) {
                c13 = __riscv_vlseg3e32_v_f32m1x3(C + (M & 8), N);
            } else {
                c13 = __riscv_vlsseg3e32_v_f32m1x3(C + (M & 8), ldc * sizeof(float), N);
            }
            cC = __riscv_vget_v_f32m1x3_f32m1(c13, 0);
            cD = __riscv_vget_v_f32m1x3_f32m1(c13, 1);
            cE = __riscv_vget_v_f32m1x3_f32m1(c13, 2);
        } else if ((M & 7) == 4) {
            vfloat32m1x4_t c14;
            if (S) {
                c14 = __riscv_vlseg4e32_v_f32m1x4(C + (M & 8), N);
            } else {
                c14 = __riscv_vlsseg4e32_v_f32m1x4(C + (M & 8), ldc * sizeof(float), N);
            }
            c8 = __riscv_vget_v_f32m1x4_f32m1(c14, 0);
            c9 = __riscv_vget_v_f32m1x4_f32m1(c14, 1);
            cA = __riscv_vget_v_f32m1x4_f32m1(c14, 2);
            cB = __riscv_vget_v_f32m1x4_f32m1(c14, 3);
        } else if ((M & 7) == 5) {
            vfloat32m1x5_t c15;
            if (S) {
                c15 = __riscv_vlseg5e32_v_f32m1x5(C + (M & 8), N);
            } else {
                c15 = __riscv_vlsseg5e32_v_f32m1x5(C + (M & 8), ldc * sizeof(float), N);
            }
            c8 = __riscv_vget_v_f32m1x5_f32m1(c15, 0);
            c9 = __riscv_vget_v_f32m1x5_f32m1(c15, 1);
            cA = __riscv_vget_v_f32m1x5_f32m1(c15, 2);
            cB = __riscv_vget_v_f32m1x5_f32m1(c15, 3);
            cE = __riscv_vget_v_f32m1x5_f32m1(c15, 4);
        } else if ((M & 7) == 6) {
            vfloat32m1x6_t c16;
            if (S) {
                c16 = __riscv_vlseg6e32_v_f32m1x6(C + (M & 8), N);
            } else {
                c16 = __riscv_vlsseg6e32_v_f32m1x6(C + (M & 8), ldc * sizeof(float), N);
            }
            c8 = __riscv_vget_v_f32m1x6_f32m1(c16, 0);
            c9 = __riscv_vget_v_f32m1x6_f32m1(c16, 1);
            cA = __riscv_vget_v_f32m1x6_f32m1(c16, 2);
            cB = __riscv_vget_v_f32m1x6_f32m1(c16, 3);
            cC = __riscv_vget_v_f32m1x6_f32m1(c16, 4);
            cD = __riscv_vget_v_f32m1x6_f32m1(c16, 5);
        } else if ((M & 7) == 7) {
            vfloat32m1x7_t c17;
            if (S) {
                c17 = __riscv_vlseg7e32_v_f32m1x7(C + (M & 8), N);
            } else {
                c17 = __riscv_vlsseg7e32_v_f32m1x7(C + (M & 8), ldc * sizeof(float), N);
            }
            c8 = __riscv_vget_v_f32m1x7_f32m1(c17, 0);
            c9 = __riscv_vget_v_f32m1x7_f32m1(c17, 1);
            cA = __riscv_vget_v_f32m1x7_f32m1(c17, 2);
            cB = __riscv_vget_v_f32m1x7_f32m1(c17, 3);
            cC = __riscv_vget_v_f32m1x7_f32m1(c17, 4);
            cD = __riscv_vget_v_f32m1x7_f32m1(c17, 5);
            cE = __riscv_vget_v_f32m1x7_f32m1(c17, 6);
        }
        if (M & 4) {
            c8 = __riscv_vfmacc_vf_f32m1(c8, alpha, result8, N);
            c9 = __riscv_vfmacc_vf_f32m1(c9, alpha, result9, N);
            cA = __riscv_vfmacc_vf_f32m1(cA, alpha, resultA, N);
            cB = __riscv_vfmacc_vf_f32m1(cB, alpha, resultB, N);
        }
        if (M & 2) {
            cC = __riscv_vfmacc_vf_f32m1(cC, alpha, resultC, N);
            cD = __riscv_vfmacc_vf_f32m1(cD, alpha, resultD, N);
        }
        if (M & 1) {
            cE = __riscv_vfmacc_vf_f32m1(cE, alpha, resultE, N);
        }
        if ((M & 7) == 1) {
            if (S) {
                __riscv_vse32_v_f32m1(C + (M & 8), cE, N);
            } else {
                __riscv_vsse32_v_f32m1(C + (M & 8), ldc * sizeof(float), cE, N);
            }
        } else if ((M & 7) == 2) {
            vfloat32m1x2_t c12 = __riscv_vcreate_v_f32m1x2(cC, cD);
            if (S) {
                __riscv_vsseg2e32_v_f32m1x2(C + (M & 8), c12, N);
            } else {
                __riscv_vssseg2e32_v_f32m1x2(C + (M & 8), ldc * sizeof(float), c12, N);
            }
        } else if ((M & 7) == 3) {
            vfloat32m1x3_t c13 = __riscv_vcreate_v_f32m1x3(cC, cD, cE);
            if (S) {
                __riscv_vsseg3e32_v_f32m1x3(C + (M & 8), c13, N);
            } else {
                __riscv_vssseg3e32_v_f32m1x3(C + (M & 8), ldc * sizeof(float), c13, N);
            }
        } else if ((M & 7) == 4) {
            vfloat32m1x4_t c14 = __riscv_vcreate_v_f32m1x4(c8, c9, cA, cB);
            if (S) {
                __riscv_vsseg4e32_v_f32m1x4(C + (M & 8), c14, N);
            } else {
                __riscv_vssseg4e32_v_f32m1x4(C + (M & 8), ldc * sizeof(float), c14, N);
            }
        } else if ((M & 7) == 5) {
            vfloat32m1x5_t c15 = __riscv_vcreate_v_f32m1x5(c8, c9, cA, cB, cE);
            if (S) {
                __riscv_vsseg5e32_v_f32m1x5(C + (M & 8), c15, N);
            } else {
                __riscv_vssseg5e32_v_f32m1x5(C + (M & 8), ldc * sizeof(float), c15, N);
            }
        } else if ((M & 7) == 6) {
            vfloat32m1x6_t c16 = __riscv_vcreate_v_f32m1x6(c8, c9, cA, cB, cC, cD);
            if (S) {
                __riscv_vsseg6e32_v_f32m1x6(C + (M & 8), c16, N);
            } else {
                __riscv_vssseg6e32_v_f32m1x6(C + (M & 8), ldc * sizeof(float), c16, N);
            }
        } else if ((M & 7) == 7) {
            vfloat32m1x7_t c17 = __riscv_vcreate_v_f32m1x7(c8, c9, cA, cB, cC, cD, cE);
            if (S) {
                __riscv_vsseg7e32_v_f32m1x7(C + (M & 8), c17, N);
            } else {
                __riscv_vssseg7e32_v_f32m1x7(C + (M & 8), ldc * sizeof(float), c17, N);
            }
        }
    } else {
        float B0, B1;
        B0 = B[0];
        if (N == 2) {
            B1 = B[1];
        }
        B += N;

        vfloat32m1_t result0, result1, result2, result3, result8, result9, resultA, resultB;
        float r8, r9, rA, rC, rD, rE, a0, a1, a2;
        if (M & 8) {
            result2 = __riscv_vle32_v_f32m1(A0, 8);
            result0 = __riscv_vfmul_vf_f32m1(result2, B0, 8);
            if (N == 2) {
                result1 = __riscv_vfmul_vf_f32m1(result2, B1, 8);
            }
#ifndef GEMM_NEW_PACKING
            A0 += 8;
#endif
        }
#ifdef GEMM_NEW_PACKING
        if (M & 4) {
            resultA = __riscv_vle32_v_f32m1(A0 + (M & 8), 8);
            result8 = __riscv_vfmul_vf_f32m1(resultA, B0, 8);
            if (N == 2) {
                result9 = __riscv_vfmul_vf_f32m1(resultA, B1, 8);
            }
        }
        if (M & 2) {
            a0 = A0[0 + (M & 0xC)];
            a1 = A0[1 + (M & 0xC)];
            rC = B0 * a0;
            rD = B0 * a1;
            if (N == 2) {
                r8 = B1 * a0;
                r9 = B1 * a1;
            }
        }
        if (M & 1) {
            a2 = A0[0 + (M & 0xE)];
            rE = B0 * a2;
            if (N == 2) {
                rA = B1 * a2;
            }
        }
        A0 += M;
#else
        if (M & 4) {
            resultA = __riscv_vle32_v_f32m1(A1, 8);
            result8 = __riscv_vfmul_vf_f32m1(resultA, B0, 8);
            if (N == 2) {
                result9 = __riscv_vfmul_vf_f32m1(resultA, B1, 8);
            }
            A1 += 4;
        }
        if (M & 2) {
            a0 = A2[0];
            a1 = A2[1];
            rC = B0 * a0;
            rD = B0 * a1;
            if (N == 2) {
                r8 = B1 * a0;
                r9 = B1 * a1;
            }
            A2 += 2;
        }
        if (M & 1) {
            a2 = A3[0];
            rE = B0 * a2;
            if (N == 2) {
                rA = B1 * a2;
            }
            A3 += 1;
        }
#endif

        for (BLASLONG k = 1; k < K; k++) {
            B0 = B[0];
            if (N == 2) {
                B1 = B[1];
            }
            B += N;

            if (M & 8) {
                result2 = __riscv_vle32_v_f32m1(A0, 8);
                result0 = __riscv_vfmacc_vf_f32m1(result0, B0, result2, 8);
                if (N == 2) {
                    result1 = __riscv_vfmacc_vf_f32m1(result1, B1, result2, 8);
                }
#ifndef GEMM_NEW_PACKING
                A0 += 8;
#endif
            }
#ifdef GEMM_NEW_PACKING
            if (M & 4) {
                resultA = __riscv_vle32_v_f32m1(A0 + (M & 8), 8);
                result8 = __riscv_vfmacc_vf_f32m1(result8, B0, resultA, 8);
                if (N == 2) {
                    result9 = __riscv_vfmacc_vf_f32m1(result9, B1, resultA, 8);
                }
            }
            if (M & 2) {
                a0 = A0[0 + (M & 0xC)];
                a1 = A0[1 + (M & 0xC)];
                rC += B0 * a0;
                rD += B0 * a1;
                if (N == 2) {
                    r8 += B1 * a0;
                    r9 += B1 * a1;
                }
            }
            if (M & 1) {
                a2 = A0[0 + (M & 0xE)];
                rE += B0 * a2;
                if (N == 2) {
                    rA += B1 * a2;
                }
            }
            A0 += M;
#else
            if (M & 4) {
                resultA = __riscv_vle32_v_f32m1(A1, 8);
                result8 = __riscv_vfmacc_vf_f32m1(result8, B0, resultA, 8);
                if (N == 2) {
                    result9 = __riscv_vfmacc_vf_f32m1(result9, B1, resultA, 8);
                }
                A1 += 4;
            }
            if (M & 2) {
                a0 = A2[0];
                a1 = A2[1];
                rC += B0 * a0;
                rD += B0 * a1;
                if (N == 2) {
                    r8 += B1 * a0;
                    r9 += B1 * a1;
                }
                A2 += 2;
            }
            if (M & 1) {
                a2 = A3[0];
                rE += B0 * a2;
                if (N == 2) {
                    rA += B1 * a2;
                }
                A3 += 1;
            }
#endif
        }

        if (M & 8) {
            result2 = __riscv_vle32_v_f32m1(C, 8);
            result2 = __riscv_vfmacc_vf_f32m1(result2, alpha, result0, 8);
            __riscv_vse32_v_f32m1(C, result2, 8);
            if (N == 2) {
                result3 = __riscv_vle32_v_f32m1(C + ldc, 8);
                result3 = __riscv_vfmacc_vf_f32m1(result3, alpha, result1, 8);
                __riscv_vse32_v_f32m1(C + ldc, result3, 8);
            }
        }
        if (M & 4) {
            resultA = __riscv_vle32_v_f32m1(C + (M & 8), 4);
            resultA = __riscv_vfmacc_vf_f32m1(resultA, alpha, result8, 4);
            __riscv_vse32_v_f32m1(C + (M & 8), resultA, 4);
            if (N == 2) {
                resultB = __riscv_vle32_v_f32m1(C + (M & 8) + ldc, 4);
                resultB = __riscv_vfmacc_vf_f32m1(resultB, alpha, result9, 4);
                __riscv_vse32_v_f32m1(C + (M & 8) + ldc, resultB, 4);
            }
        }
        if (M & 2) {
            C[0 + (M & 0xC)] += alpha * rC;
            C[1 + (M & 0xC)] += alpha * rD;
            if (N == 2) {
                C[0 + ldc + (M & 0xC)] += alpha * r8;
                C[1 + ldc + (M & 0xC)] += alpha * r9;
            }
        }
        if (M & 1) {
            C[0 + (M & 0xE)] += alpha * rE;
            if (N == 2) {
                C[0 + ldc + (M & 0xE)] += alpha * rA;
            }
        }
    }
}

static void M_TAIL(BLASLONG K, const BLASLONG M, const BLASLONG N, const BLASLONG S, FLOAT alpha, FLOAT* A0, FLOAT* B, FLOAT* C, BLASLONG ldc)
{
    FLOAT *A1, *A2, *A3;
    if (M & 4) {
        A1 = A0 + (K * (M & 0x8));
    }
    if (M & 2) {
        A2 = A0 + (K * (M & 0xC));
    }
    if (M & 1) {
        A3 = A0 + (K * (M & 0xE));
    }
    if (M & 8) {
        if (M & 4) {
            if (M & 2) {
                if (M & 1) {
                    M_TAIL_ONE(K, 15, N, 0, alpha, A0, A1, A2, A3, B, C, ldc);
                } else {
                    M_TAIL_ONE(K, 14, N, 0, alpha, A0, A1, A2, A0, B, C, ldc);
                }
            } else {
                if (M & 1) {
                    M_TAIL_ONE(K, 13, N, 0, alpha, A0, A1, A0, A3, B, C, ldc);
                } else {
                    M_TAIL_ONE(K, 12, N, 0, alpha, A0, A1, A0, A0, B, C, ldc);
                }
            }
        } else {
            if (M & 2) {
                if (M & 1) {
                    M_TAIL_ONE(K, 11, N, 0, alpha, A0, A0, A2, A3, B, C, ldc);
                } else {
                    M_TAIL_ONE(K, 10, N, 0, alpha, A0, A0, A2, A0, B, C, ldc);
                }
            } else {
                if (M & 1) {
                    M_TAIL_ONE(K,  9, N, 0, alpha, A0, A0, A0, A3, B, C, ldc);
                } else {
                    if (S) {
                        M_TAIL_ONE(K,  8, N, 1, alpha, A0, A0, A0, A0, B, C, ldc);
                    } else {
                        M_TAIL_ONE(K,  8, N, 0, alpha, A0, A0, A0, A0, B, C, ldc);
                    }
                }
            }
        }
    } else if (M & 4) {
        if (M & 2) {
            if (M & 1) {
                if (S) {
                    M_TAIL_ONE(K,  7, N, 1, alpha, A0, A1, A2, A3, B, C, ldc);
                } else {
                    M_TAIL_ONE(K,  7, N, 0, alpha, A0, A1, A2, A3, B, C, ldc);
                }
            } else {
                if (S) {
                    M_TAIL_ONE(K,  6, N, 1, alpha, A0, A1, A2, A0, B, C, ldc);
                } else {
                    M_TAIL_ONE(K,  6, N, 0, alpha, A0, A1, A2, A0, B, C, ldc);
                }
            }
        } else {
            if (M & 1) {
                if (S) {
                    M_TAIL_ONE(K,  5, N, 1, alpha, A0, A1, A0, A3, B, C, ldc);
                } else {
                    M_TAIL_ONE(K,  5, N, 0, alpha, A0, A1, A0, A3, B, C, ldc);
                }
            } else {
                if (S) {
                    M_TAIL_ONE(K,  4, N, 1, alpha, A0, A1, A0, A0, B, C, ldc);
                } else {
                    M_TAIL_ONE(K,  4, N, 0, alpha, A0, A1, A0, A0, B, C, ldc);
                }
            }
        }
    } else if (M & 2) {
        if (M & 1) {
            if (S) {
                M_TAIL_ONE(K,  3, N, 1, alpha, A0, A0, A2, A3, B, C, ldc);
            } else {
                M_TAIL_ONE(K,  3, N, 0, alpha, A0, A0, A2, A3, B, C, ldc);
            }
        } else {
            if (S) {
                M_TAIL_ONE(K,  2, N, 1, alpha, A0, A0, A2, A0, B, C, ldc);
            } else {
                M_TAIL_ONE(K,  2, N, 0, alpha, A0, A0, A2, A0, B, C, ldc);
            }
        }
    } else if (M & 1) {
        if (S) {
            M_TAIL_ONE(K,  1, N, 1, alpha, A0, A0, A0, A3, B, C, ldc);
        } else {
            M_TAIL_ONE(K,  1, N, 0, alpha, A0, A0, A0, A3, B, C, ldc);
        }
    }
}
#endif

#ifdef GEMM_BOTTOM_EDGE
static void FORCEINLINE N_TAIL_ONE(BLASLONG K, const BLASLONG M, const BLASLONG N, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc)
{
    BLASLONG gvl = __riscv_vsetvl_e32m1(8);

    for (BLASLONG i=0; i<M/16; i+=1) {
        BLASLONG bi=n_top*K;
        float B0 = B[bi+0];
        float B1 = B[bi+1];
        float B2 = B[bi+2];
        float B3 = B[bi+3];
        bi += 4;

        vfloat32m1_t A0 = __riscv_vle32_v_f32m1( A, gvl );
        vfloat32m1_t A1 = __riscv_vle32_v_f32m1( A, gvl );
        A += 16;

        vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
        vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A1, B0, gvl);
        vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
        vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A1, B1, gvl);
        vfloat32m1_t result4 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
        vfloat32m1_t result5 = __riscv_vfmul_vf_f32m1( A1, B2, gvl);
        vfloat32m1_t result6 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);
        vfloat32m1_t result7 = __riscv_vfmul_vf_f32m1( A1, B3, gvl);

        for(BLASLONG k=1; k<K; k++) {
            B0 = B[bi+0];
            B1 = B[bi+1];
            B2 = B[bi+2];
            B3 = B[bi+3];
            bi += 4;

            A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
            ai += 16;

            result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
            result1 = __riscv_vfmacc_vf_f32m1( result1, B0, A1, gvl);
            result2 = __riscv_vfmacc_vf_f32m1( result2, B1, A0, gvl);
            result3 = __riscv_vfmacc_vf_f32m1( result3, B1, A1, gvl);
            result4 = __riscv_vfmacc_vf_f32m1( result4, B2, A0, gvl);
            result5 = __riscv_vfmacc_vf_f32m1( result5, B2, A1, gvl);
            result6 = __riscv_vfmacc_vf_f32m1( result6, B3, A0, gvl);
            result7 = __riscv_vfmacc_vf_f32m1( result7, B3, A1, gvl);
        }
    }
}
#endif

int CNAME(BLASLONG M, BLASLONG N, BLASLONG K, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc)
{
    BLASLONG gvl = 0;
    BLASLONG m_top = 0;
    BLASLONG n_top = 0;
#ifdef GEMM_RIGHT_EDGE
    const BLASLONG m_edge = M & 15;
    const BLASLONG S = ((M == ldc) ? 1 : 0);
#endif


    // -- MAIN PASS

    for (BLASLONG j=0; j<N/8; j+=1) {
        m_top = 0;
#ifdef USE_LMUL2
        gvl = __riscv_vsetvl_e32m2(16);
#else
        gvl = __riscv_vsetvl_e32m1(8);
#endif


        for (BLASLONG i=0; i<M/16; i+=1) {
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            float B4 = B[bi+4];
            float B5 = B[bi+5];
            float B6 = B[bi+6];
            float B7 = B[bi+7];
            bi += 8;

#ifdef USE_LMUL2
            vfloat32m2_t A0 = __riscv_vle32_v_f32m2( &A[ai+0*gvl], gvl );
            ai += 16;

            vfloat32m2_t result0 = __riscv_vfmul_vf_f32m2( A0, B0, gvl);
            vfloat32m2_t result1 = __riscv_vfmul_vf_f32m2( A0, B1, gvl);
            vfloat32m2_t result2 = __riscv_vfmul_vf_f32m2( A0, B2, gvl);
            vfloat32m2_t result3 = __riscv_vfmul_vf_f32m2( A0, B3, gvl);
            vfloat32m2_t result4 = __riscv_vfmul_vf_f32m2( A0, B4, gvl);
            vfloat32m2_t result5 = __riscv_vfmul_vf_f32m2( A0, B5, gvl);
            vfloat32m2_t result6 = __riscv_vfmul_vf_f32m2( A0, B6, gvl);
            vfloat32m2_t result7 = __riscv_vfmul_vf_f32m2( A0, B7, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                B4 = B[bi+4];
                B5 = B[bi+5];
                B6 = B[bi+6];
                B7 = B[bi+7];
                bi += 8;

                A0 = __riscv_vle32_v_f32m2( &A[ai+0*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m2( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m2( result1, B1, A0, gvl);
                result2 = __riscv_vfmacc_vf_f32m2( result2, B2, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m2( result3, B3, A0, gvl);
                result4 = __riscv_vfmacc_vf_f32m2( result4, B4, A0, gvl);
                result5 = __riscv_vfmacc_vf_f32m2( result5, B5, A0, gvl);
                result6 = __riscv_vfmacc_vf_f32m2( result6, B6, A0, gvl);
                result7 = __riscv_vfmacc_vf_f32m2( result7, B7, A0, gvl);
            }

            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m2_t c0 = __riscv_vle32_v_f32m2( &C[ci], gvl); ci += ldc;
            vfloat32m2_t c1 = __riscv_vle32_v_f32m2( &C[ci], gvl); ci += ldc;
            vfloat32m2_t c2 = __riscv_vle32_v_f32m2( &C[ci], gvl); ci += ldc;
            vfloat32m2_t c3 = __riscv_vle32_v_f32m2( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m2( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m2( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m2( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m2( c3, alpha, result3, gvl );

            ci-=3*ldc;

            __riscv_vse32_v_f32m2( &C[ci], c0, gvl); ci += ldc;
            __riscv_vse32_v_f32m2( &C[ci], c1, gvl); ci += ldc;
            __riscv_vse32_v_f32m2( &C[ci], c2, gvl); ci += ldc;
            __riscv_vse32_v_f32m2( &C[ci], c3, gvl); ci += ldc;

            vfloat32m2_t c4 = __riscv_vle32_v_f32m2( &C[ci], gvl); ci += ldc;
            vfloat32m2_t c5 = __riscv_vle32_v_f32m2( &C[ci], gvl); ci += ldc;
            vfloat32m2_t c6 = __riscv_vle32_v_f32m2( &C[ci], gvl); ci += ldc;
            vfloat32m2_t c7 = __riscv_vle32_v_f32m2( &C[ci], gvl);
            c4 = __riscv_vfmacc_vf_f32m2( c4, alpha, result4, gvl );
            c5 = __riscv_vfmacc_vf_f32m2( c5, alpha, result5, gvl );
            c6 = __riscv_vfmacc_vf_f32m2( c6, alpha, result6, gvl );
            c7 = __riscv_vfmacc_vf_f32m2( c7, alpha, result7, gvl );

            ci-=3*ldc;

            __riscv_vse32_v_f32m2( &C[ci], c4, gvl); ci += ldc;
            __riscv_vse32_v_f32m2( &C[ci], c5, gvl); ci += ldc;
            __riscv_vse32_v_f32m2( &C[ci], c6, gvl); ci += ldc;
            __riscv_vse32_v_f32m2( &C[ci], c7, gvl);
#else
            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            vfloat32m1_t A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
            ai += 16;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A1, B0, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A1, B1, gvl);
            vfloat32m1_t result4 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result5 = __riscv_vfmul_vf_f32m1( A1, B2, gvl);
            vfloat32m1_t result6 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);
            vfloat32m1_t result7 = __riscv_vfmul_vf_f32m1( A1, B3, gvl);
            vfloat32m1_t result8 = __riscv_vfmul_vf_f32m1( A0, B4, gvl);
            vfloat32m1_t result9 = __riscv_vfmul_vf_f32m1( A1, B4, gvl);
            vfloat32m1_t result10 = __riscv_vfmul_vf_f32m1( A0, B5, gvl);
            vfloat32m1_t result11 = __riscv_vfmul_vf_f32m1( A1, B5, gvl);
            vfloat32m1_t result12 = __riscv_vfmul_vf_f32m1( A0, B6, gvl);
            vfloat32m1_t result13 = __riscv_vfmul_vf_f32m1( A1, B6, gvl);
            vfloat32m1_t result14 = __riscv_vfmul_vf_f32m1( A0, B7, gvl);
            vfloat32m1_t result15 = __riscv_vfmul_vf_f32m1( A1, B7, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                B4 = B[bi+4];
                B5 = B[bi+5];
                B6 = B[bi+6];
                B7 = B[bi+7];
                bi += 8;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B0, A1, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B1, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B1, A1, gvl);
                result4 = __riscv_vfmacc_vf_f32m1( result4, B2, A0, gvl);
                result5 = __riscv_vfmacc_vf_f32m1( result5, B2, A1, gvl);
                result6 = __riscv_vfmacc_vf_f32m1( result6, B3, A0, gvl);
                result7 = __riscv_vfmacc_vf_f32m1( result7, B3, A1, gvl);
                result8 = __riscv_vfmacc_vf_f32m1( result8, B4, A0, gvl);
                result9 = __riscv_vfmacc_vf_f32m1( result9, B4, A1, gvl);
                result10 = __riscv_vfmacc_vf_f32m1( result10, B5, A0, gvl);
                result11 = __riscv_vfmacc_vf_f32m1( result11, B5, A1, gvl);
                result12 = __riscv_vfmacc_vf_f32m1( result12, B6, A0, gvl);
                result13 = __riscv_vfmacc_vf_f32m1( result13, B6, A1, gvl);
                result14 = __riscv_vfmacc_vf_f32m1( result14, B7, A0, gvl);
                result15 = __riscv_vfmacc_vf_f32m1( result15, B7, A1, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c4 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c5 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c6 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c7 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c8 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c9 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c10 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c11 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c12 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c13 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c14 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c15 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );
            c4 = __riscv_vfmacc_vf_f32m1( c4, alpha, result4, gvl );
            c5 = __riscv_vfmacc_vf_f32m1( c5, alpha, result5, gvl );
            c6 = __riscv_vfmacc_vf_f32m1( c6, alpha, result6, gvl );
            c7 = __riscv_vfmacc_vf_f32m1( c7, alpha, result7, gvl );
            c8 = __riscv_vfmacc_vf_f32m1( c8, alpha, result8, gvl );
            c9 = __riscv_vfmacc_vf_f32m1( c9, alpha, result9, gvl );
            c10 = __riscv_vfmacc_vf_f32m1( c10, alpha, result10, gvl );
            c11 = __riscv_vfmacc_vf_f32m1( c11, alpha, result11, gvl );
            c12 = __riscv_vfmacc_vf_f32m1( c12, alpha, result12, gvl );
            c13 = __riscv_vfmacc_vf_f32m1( c13, alpha, result13, gvl );
            c14 = __riscv_vfmacc_vf_f32m1( c14, alpha, result14, gvl );
            c15 = __riscv_vfmacc_vf_f32m1( c15, alpha, result15, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c4, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c5, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c6, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c7, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c8, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c9, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c10, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c11, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c12, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c13, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c14, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c15, gvl);
#endif
            m_top += 16;
        }



        // -- tails for main pass

#ifndef GEMM_RIGHT_EDGE
        if( M & 8 ) {
            gvl = __riscv_vsetvl_e32m1(8);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            float B4 = B[bi+4];
            float B5 = B[bi+5];
            float B6 = B[bi+6];
            float B7 = B[bi+7];
            bi += 8;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 8;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);
            vfloat32m1_t result4 = __riscv_vfmul_vf_f32m1( A0, B4, gvl);
            vfloat32m1_t result5 = __riscv_vfmul_vf_f32m1( A0, B5, gvl);
            vfloat32m1_t result6 = __riscv_vfmul_vf_f32m1( A0, B6, gvl);
            vfloat32m1_t result7 = __riscv_vfmul_vf_f32m1( A0, B7, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                B4 = B[bi+4];
                B5 = B[bi+5];
                B6 = B[bi+6];
                B7 = B[bi+7];
                bi += 8;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 8;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B2, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B3, A0, gvl);
                result4 = __riscv_vfmacc_vf_f32m1( result4, B4, A0, gvl);
                result5 = __riscv_vfmacc_vf_f32m1( result5, B5, A0, gvl);
                result6 = __riscv_vfmacc_vf_f32m1( result6, B6, A0, gvl);
                result7 = __riscv_vfmacc_vf_f32m1( result7, B7, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c4 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c5 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c6 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c7 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );
            c4 = __riscv_vfmacc_vf_f32m1( c4, alpha, result4, gvl );
            c5 = __riscv_vfmacc_vf_f32m1( c5, alpha, result5, gvl );
            c6 = __riscv_vfmacc_vf_f32m1( c6, alpha, result6, gvl );
            c7 = __riscv_vfmacc_vf_f32m1( c7, alpha, result7, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c4, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c5, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c6, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c7, gvl);
            m_top += 8;
        }


        if( M & 4 ) {
            gvl = __riscv_vsetvl_e32m1(4);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            float B4 = B[bi+4];
            float B5 = B[bi+5];
            float B6 = B[bi+6];
            float B7 = B[bi+7];
            bi += 8;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 4;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);
            vfloat32m1_t result4 = __riscv_vfmul_vf_f32m1( A0, B4, gvl);
            vfloat32m1_t result5 = __riscv_vfmul_vf_f32m1( A0, B5, gvl);
            vfloat32m1_t result6 = __riscv_vfmul_vf_f32m1( A0, B6, gvl);
            vfloat32m1_t result7 = __riscv_vfmul_vf_f32m1( A0, B7, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                B4 = B[bi+4];
                B5 = B[bi+5];
                B6 = B[bi+6];
                B7 = B[bi+7];
                bi += 8;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 4;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B2, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B3, A0, gvl);
                result4 = __riscv_vfmacc_vf_f32m1( result4, B4, A0, gvl);
                result5 = __riscv_vfmacc_vf_f32m1( result5, B5, A0, gvl);
                result6 = __riscv_vfmacc_vf_f32m1( result6, B6, A0, gvl);
                result7 = __riscv_vfmacc_vf_f32m1( result7, B7, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c4 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c5 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c6 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c7 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );
            c4 = __riscv_vfmacc_vf_f32m1( c4, alpha, result4, gvl );
            c5 = __riscv_vfmacc_vf_f32m1( c5, alpha, result5, gvl );
            c6 = __riscv_vfmacc_vf_f32m1( c6, alpha, result6, gvl );
            c7 = __riscv_vfmacc_vf_f32m1( c7, alpha, result7, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c4, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c5, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c6, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c7, gvl);
            m_top += 4;
        }


        if( M & 2 ) {
            float result0 = 0;
            float result1 = 0;
            float result2 = 0;
            float result3 = 0;
            float result4 = 0;
            float result5 = 0;
            float result6 = 0;
            float result7 = 0;
            float result8 = 0;
            float result9 = 0;
            float result10 = 0;
            float result11 = 0;
            float result12 = 0;
            float result13 = 0;
            float result14 = 0;
            float result15 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+1]*B[bi+0];
                result2+=A[ai+0]*B[bi+1];
                result3+=A[ai+1]*B[bi+1];
                result4+=A[ai+0]*B[bi+2];
                result5+=A[ai+1]*B[bi+2];
                result6+=A[ai+0]*B[bi+3];
                result7+=A[ai+1]*B[bi+3];
                result8+=A[ai+0]*B[bi+4];
                result9+=A[ai+1]*B[bi+4];
                result10+=A[ai+0]*B[bi+5];
                result11+=A[ai+1]*B[bi+5];
                result12+=A[ai+0]*B[bi+6];
                result13+=A[ai+1]*B[bi+6];
                result14+=A[ai+0]*B[bi+7];
                result15+=A[ai+1]*B[bi+7];
                ai+=2;
                bi+=8;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+0*ldc+1] += alpha * result1;
            C[ci+1*ldc+0] += alpha * result2;
            C[ci+1*ldc+1] += alpha * result3;
            C[ci+2*ldc+0] += alpha * result4;
            C[ci+2*ldc+1] += alpha * result5;
            C[ci+3*ldc+0] += alpha * result6;
            C[ci+3*ldc+1] += alpha * result7;
            C[ci+4*ldc+0] += alpha * result8;
            C[ci+4*ldc+1] += alpha * result9;
            C[ci+5*ldc+0] += alpha * result10;
            C[ci+5*ldc+1] += alpha * result11;
            C[ci+6*ldc+0] += alpha * result12;
            C[ci+6*ldc+1] += alpha * result13;
            C[ci+7*ldc+0] += alpha * result14;
            C[ci+7*ldc+1] += alpha * result15;
            m_top+=2;
        }


        if( M & 1 ) {
            float result0 = 0;
            float result1 = 0;
            float result2 = 0;
            float result3 = 0;
            float result4 = 0;
            float result5 = 0;
            float result6 = 0;
            float result7 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+0]*B[bi+1];
                result2+=A[ai+0]*B[bi+2];
                result3+=A[ai+0]*B[bi+3];
                result4+=A[ai+0]*B[bi+4];
                result5+=A[ai+0]*B[bi+5];
                result6+=A[ai+0]*B[bi+6];
                result7+=A[ai+0]*B[bi+7];
                ai+=1;
                bi+=8;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+1*ldc+0] += alpha * result1;
            C[ci+2*ldc+0] += alpha * result2;
            C[ci+3*ldc+0] += alpha * result3;
            C[ci+4*ldc+0] += alpha * result4;
            C[ci+5*ldc+0] += alpha * result5;
            C[ci+6*ldc+0] += alpha * result6;
            C[ci+7*ldc+0] += alpha * result7;
            m_top+=1;
        }
#else
        if (m_edge) {
            M_TAIL(K, m_edge, 8, S, alpha, &A[m_top*K], &B[n_top*K], &C[n_top*ldc+m_top], ldc);
        }
#endif

        n_top += 8;
    }



    // -- tails for N=4

    if( N & 4 ) {
#ifdef USE_LMUL2
        gvl = __riscv_vsetvl_e32m2(16);
#else
        gvl = __riscv_vsetvl_e32m1(8);
#endif
        m_top = 0;

#ifndef GEMM_BOTTOM_EDGE
        for (BLASLONG i=0; i<M/16; i+=1) {
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            bi += 4;

#ifdef USE_LMUL2
            vfloat32m2_t A0 = __riscv_vle32_v_f32m2( &A[ai+0*gvl], gvl );
            ai += 16;

            vfloat32m2_t result0 = __riscv_vfmul_vf_f32m2( A0, B0, gvl);
            vfloat32m2_t result1 = __riscv_vfmul_vf_f32m2( A0, B1, gvl);
            vfloat32m2_t result2 = __riscv_vfmul_vf_f32m2( A0, B2, gvl);
            vfloat32m2_t result3 = __riscv_vfmul_vf_f32m2( A0, B3, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                bi += 4;

                A0 = __riscv_vle32_v_f32m2( &A[ai+0*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m2( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m2( result1, B1, A0, gvl);
                result2 = __riscv_vfmacc_vf_f32m2( result2, B2, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m2( result3, B3, A0, gvl);
            }

            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m2_t c0 = __riscv_vle32_v_f32m2( &C[ci], gvl); ci += ldc;
            vfloat32m2_t c1 = __riscv_vle32_v_f32m2( &C[ci], gvl); ci += ldc;
            vfloat32m2_t c2 = __riscv_vle32_v_f32m2( &C[ci], gvl); ci += ldc;
            vfloat32m2_t c3 = __riscv_vle32_v_f32m2( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m2( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m2( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m2( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m2( c3, alpha, result3, gvl );

            ci-=3*ldc;

            __riscv_vse32_v_f32m2( &C[ci], c0, gvl); ci += ldc;
            __riscv_vse32_v_f32m2( &C[ci], c1, gvl); ci += ldc;
            __riscv_vse32_v_f32m2( &C[ci], c2, gvl); ci += ldc;
            __riscv_vse32_v_f32m2( &C[ci], c3, gvl);
#else
            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            vfloat32m1_t A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
            ai += 16;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A1, B0, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A1, B1, gvl);
            vfloat32m1_t result4 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result5 = __riscv_vfmul_vf_f32m1( A1, B2, gvl);
            vfloat32m1_t result6 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);
            vfloat32m1_t result7 = __riscv_vfmul_vf_f32m1( A1, B3, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                bi += 4;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B0, A1, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B1, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B1, A1, gvl);
                result4 = __riscv_vfmacc_vf_f32m1( result4, B2, A0, gvl);
                result5 = __riscv_vfmacc_vf_f32m1( result5, B2, A1, gvl);
                result6 = __riscv_vfmacc_vf_f32m1( result6, B3, A0, gvl);
                result7 = __riscv_vfmacc_vf_f32m1( result7, B3, A1, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c4 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c5 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c6 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c7 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );
            c4 = __riscv_vfmacc_vf_f32m1( c4, alpha, result4, gvl );
            c5 = __riscv_vfmacc_vf_f32m1( c5, alpha, result5, gvl );
            c6 = __riscv_vfmacc_vf_f32m1( c6, alpha, result6, gvl );
            c7 = __riscv_vfmacc_vf_f32m1( c7, alpha, result7, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c4, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c5, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c6, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c7, gvl);
#endif
            m_top += 16;
        }
#else
        N_TAIL(K, M, N, A, B, C, ldc);
#endif


#ifndef GEMM_RIGHT_EDGE
        if( M & 8 ) {
            gvl = __riscv_vsetvl_e32m1(8);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            bi += 4;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 8;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                bi += 4;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 8;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B2, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B3, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl);
            m_top += 8;
        }


        if( M & 4 ) {
            gvl = __riscv_vsetvl_e32m1(4);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            bi += 4;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 4;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                bi += 4;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 4;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B2, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B3, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl);
            m_top += 4;
        }


        if( M & 2 ) {
            float result0 = 0;
            float result1 = 0;
            float result2 = 0;
            float result3 = 0;
            float result4 = 0;
            float result5 = 0;
            float result6 = 0;
            float result7 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+1]*B[bi+0];
                result2+=A[ai+0]*B[bi+1];
                result3+=A[ai+1]*B[bi+1];
                result4+=A[ai+0]*B[bi+2];
                result5+=A[ai+1]*B[bi+2];
                result6+=A[ai+0]*B[bi+3];
                result7+=A[ai+1]*B[bi+3];
                ai+=2;
                bi+=4;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+0*ldc+1] += alpha * result1;
            C[ci+1*ldc+0] += alpha * result2;
            C[ci+1*ldc+1] += alpha * result3;
            C[ci+2*ldc+0] += alpha * result4;
            C[ci+2*ldc+1] += alpha * result5;
            C[ci+3*ldc+0] += alpha * result6;
            C[ci+3*ldc+1] += alpha * result7;
            m_top+=2;
        }


        if( M & 1 ) {
            float result0 = 0;
            float result1 = 0;
            float result2 = 0;
            float result3 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+0]*B[bi+1];
                result2+=A[ai+0]*B[bi+2];
                result3+=A[ai+0]*B[bi+3];
                ai+=1;
                bi+=4;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+1*ldc+0] += alpha * result1;
            C[ci+2*ldc+0] += alpha * result2;
            C[ci+3*ldc+0] += alpha * result3;
            m_top+=1;
        }
#else
        if (m_edge) {
            M_TAIL(K, m_edge, 4, S, alpha, &A[m_top*K], &B[n_top*K], &C[n_top*ldc+m_top], ldc);
        }
#endif

        n_top += 4;
    }



    // -- tails for N=2

    if( N & 2 ) {
#ifdef USE_LMUL2
        gvl = __riscv_vsetvl_e32m2(16);
#else
        gvl = __riscv_vsetvl_e32m1(8);
#endif
        m_top = 0;

        for (BLASLONG i=0; i<M/16; i+=1) {
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            bi += 2;

#ifdef USE_LMUL2
            vfloat32m2_t A0 = __riscv_vle32_v_f32m2( &A[ai+0*gvl], gvl );
            ai += 16;

            vfloat32m2_t result0 = __riscv_vfmul_vf_f32m2( A0, B0, gvl);
            vfloat32m2_t result1 = __riscv_vfmul_vf_f32m2( A0, B1, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                bi += 2;

                A0 = __riscv_vle32_v_f32m2( &A[ai+0*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m2( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m2( result1, B1, A0, gvl);
            }

            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m2_t c0 = __riscv_vle32_v_f32m2( &C[ci], gvl); ci += ldc;
            vfloat32m2_t c1 = __riscv_vle32_v_f32m2( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m2( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m2( c1, alpha, result1, gvl );

            ci-=1*ldc;

            __riscv_vse32_v_f32m2( &C[ci], c0, gvl); ci += ldc;
            __riscv_vse32_v_f32m2( &C[ci], c1, gvl);
#else
            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            vfloat32m1_t A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
            ai += 16;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A1, B0, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A1, B1, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                bi += 2;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B0, A1, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B1, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B1, A1, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl);
#endif
            m_top += 16;
        }


#ifndef GEMM_RIGHT_EDGE
        if( M & 8 ) {
            gvl = __riscv_vsetvl_e32m1(8);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            bi += 2;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 8;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                bi += 2;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 8;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl);
            m_top += 8;
        }


        if( M & 4 ) {
            gvl = __riscv_vsetvl_e32m1(4);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            bi += 2;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 4;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                bi += 2;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 4;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl);
            m_top += 4;
        }


        if( M & 2 ) {
            float result0 = 0;
            float result1 = 0;
            float result2 = 0;
            float result3 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+1]*B[bi+0];
                result2+=A[ai+0]*B[bi+1];
                result3+=A[ai+1]*B[bi+1];
                ai+=2;
                bi+=2;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+0*ldc+1] += alpha * result1;
            C[ci+1*ldc+0] += alpha * result2;
            C[ci+1*ldc+1] += alpha * result3;
            m_top+=2;
        }


        if( M & 1 ) {
            float result0 = 0;
            float result1 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+0]*B[bi+1];
                ai+=1;
                bi+=2;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+1*ldc+0] += alpha * result1;
            m_top+=1;
        }
#else
        if (m_edge) {
            M_TAIL(K, m_edge, 2, S, alpha, &A[m_top*K], &B[n_top*K], &C[n_top*ldc+m_top], ldc);
        }
#endif

        n_top += 2;
    }



    // -- tails for N=1

    if( N & 1 ) {
#ifdef USE_LMUL2
        gvl = __riscv_vsetvl_e32m2(16);
#else
        gvl = __riscv_vsetvl_e32m1(8);
#endif
        m_top = 0;

        for (BLASLONG i=0; i<M/16; i+=1) {
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            bi += 1;

#ifdef USE_LMUL2
            vfloat32m2_t A0 = __riscv_vle32_v_f32m2( &A[ai+0*gvl], gvl );
            ai += 16;

            vfloat32m2_t result0 = __riscv_vfmul_vf_f32m2( A0, B0, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                bi += 1;

                A0 = __riscv_vle32_v_f32m2( &A[ai+0*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m2( result0, B0, A0, gvl);
            }

            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m2_t c0 = __riscv_vle32_v_f32m2( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m2( c0, alpha, result0, gvl );

            __riscv_vse32_v_f32m2( &C[ci], c0, gvl);
#else
            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            vfloat32m1_t A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
            ai += 16;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A1, B0, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                bi += 1;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B0, A1, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl);
#endif
            m_top += 16;
        }


#ifndef GEMM_RIGHT_EDGE
        if( M & 8 ) {
            gvl = __riscv_vsetvl_e32m1(8);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            bi += 1;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 8;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                bi += 1;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 8;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl);
            m_top += 8;
        }


        if( M & 4 ) {
            gvl = __riscv_vsetvl_e32m1(4);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            bi += 1;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 4;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                bi += 1;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 4;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl);
            m_top += 4;
        }


        if( M & 2 ) {
            float result0 = 0;
            float result1 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+1]*B[bi+0];
                ai+=2;
                bi+=1;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+0*ldc+1] += alpha * result1;
            m_top+=2;
        }


        if( M & 1 ) {
            float result0 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                ai+=1;
                bi+=1;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            m_top+=1;
        }
#else
        if (m_edge) {
            M_TAIL(K, m_edge, 1, S, alpha, &A[m_top*K], &B[n_top*K], &C[n_top*ldc+m_top], ldc);
        }
#endif

        n_top += 1;
    }

    return 0;
}

