/*

AUTOGENERATED KERNEL
Settings:
 LMUL=1
 M=16
 M_tail_scalar_from=2
 N=8
 __riscv_='__riscv_'
 complex=False
 conjugate=False
 cpu='zvl256b'
 force_acc_double=False
 index_type='BLASLONG'
 op='gemm'
 param_precision='float'
 reg_width_bits=256
 tail_policy=''
 trace=False

Derived:
 ELEN_ACC=32
 ELEN_PARAM=32
 LMUL_ACC=1
 VFMACC='__riscv_vfmacc_vf_f32m1'
 VFMUL='__riscv_vfmul_vf_f32m1'
 VLEV='__riscv_vle32_v_f32m1'
 VLSEV='__riscv_vlse32_v_f32m1'
 VMACC_TO_ACC='__riscv_vfmacc_vf_f32m1'
 VMUL_TO_ACC='__riscv_vfmul_vf_f32m1'
 VSETVL='__riscv_vsetvl_e32m1'
 VSEV='__riscv_vse32_v_f32m1'
 VSSEV='__riscv_vsse32_v_f32m1'
 acc_vector_t='vfloat32m1_t'
 output='sgemm_kernel_16x8_zvl256b.c'
 param_scalar_t='float'
 param_vector_t='vfloat32m1_t'

*/

#include "common.h"

//#define GEMM_RIGHT_EDGE    // One pass for right edge - unpacking A
//#define GEMM_BOTTOM_EDGE   // One pass for bottom edge - unrolling B

#ifdef GEMM_RIGHT_EDGE
//#define GEMM_NEW_PACKING   // Right edge packed data friendly

#define FORCEINLINE      inline __attribute__((always_inline))

#ifndef GEMM_NEW_PACKING
static vfloat32m1_t FORCEINLINE A_UNROLL(const BLASLONG M, const BLASLONG S, FLOAT** A1, FLOAT** A2, FLOAT** A3, vbool32_t mask1, vbool32_t mask2)
{
    vfloat32m1_t A0 = __riscv_vle32_v_f32m1(*A1, M);
    if ((S == 1) || (M == 1) || (M == 2) || (M == 4) || (M == 8)) {
        *A1 += M;
    } else {
        A0 = __riscv_vle32_v_f32m1_tumu(mask1, A0, *A2, M);
        if (S == 2) {
            if (M < 5) {
                *A1 += 2;
                *A2 += 1;
            } else {
                *A1 += 4;
                *A2 += ((M == 5) ? 1 : 2);
            }
        } else {
            A0 = __riscv_vle32_v_f32m1_tumu(mask2, A0, *A3, M);
            *A1 += 4;
            *A2 += 2;
            *A3 += 1;
        }
    }
    return A0;
}

static vfloat32m2_t FORCEINLINE A_UNROLL2(const BLASLONG M, const BLASLONG S, FLOAT** A0, FLOAT** A1, FLOAT** A2, FLOAT** A3, vbool32_t mask1, vbool32_t mask2)
{
    vfloat32m1_t A4 = A_UNROLL(8, 1, A0, A0, A0, mask1, mask2);
    vfloat32m1_t A5 = A_UNROLL(M, S, A1, A2, A3, mask1, mask2);
    return __riscv_vcreate_v_f32m1_f32m2(A4, A5);
}
#endif

#ifdef GEMM_NEW_PACKING
static void FORCEINLINE M_TAIL_ONE(BLASLONG K, const BLASLONG M, const BLASLONG N, FLOAT alpha, FLOAT* A0, FLOAT* B, FLOAT* C, BLASLONG ldc)
#else
static void FORCEINLINE M_TAIL_ONE(BLASLONG K, const BLASLONG M, const BLASLONG N, const BLASLONG S, FLOAT alpha, FLOAT* A0, FLOAT* A1, FLOAT* A2, FLOAT* A3, FLOAT* B, FLOAT* C, BLASLONG ldc, vbool32_t mask1, vbool32_t mask2)
#endif
{
    float B0, B1, B2, B3, B4, B5, B6, B7;
    B0 = B[0];
    if (N >= 2) {
        B1 = B[1];
    }
    if (N >= 4) {
        B2 = B[2];
        B3 = B[3];
    }
    if (N == 8) {
        B4 = B[4];
        B5 = B[5];
        B6 = B[6];
        B7 = B[7];
    }
    B += N;

    if (M > 8) {
#ifdef GEMM_NEW_PACKING
        vfloat32m2_t A6 = __riscv_vle32_v_f32m2(A0, M);
        A0 += M;
#else
        const BLASLONG M2 = M & 7;

        vfloat32m2_t A6 = A_UNROLL2(M2, S, &A0, &A1, &A2, &A3, mask1, mask2);
#endif

        vfloat32m2_t result0, result1, result2, result3, result4, result5, result6, result7;
        result0 = __riscv_vfmul_vf_f32m2(A6, B0, M);
        if (N >= 2) {
            result1 = __riscv_vfmul_vf_f32m2(A6, B1, M);
        }
        if (N >= 4) {
            result2 = __riscv_vfmul_vf_f32m2(A6, B2, M);
            result3 = __riscv_vfmul_vf_f32m2(A6, B3, M);
        }
        if (N == 8) {
            result4 = __riscv_vfmul_vf_f32m2(A6, B4, M);
            result5 = __riscv_vfmul_vf_f32m2(A6, B5, M);
            result6 = __riscv_vfmul_vf_f32m2(A6, B6, M);
            result7 = __riscv_vfmul_vf_f32m2(A6, B7, M);
        }

        for (BLASLONG k = 1; k < K; k++) {
            B0 = B[0];
            if (N >= 2) {
                B1 = B[1];
            }
            if (N >= 4) {
                B2 = B[2];
                B3 = B[3];
            }
            if (N == 8) {
                B4 = B[4];
                B5 = B[5];
                B6 = B[6];
                B7 = B[7];
            }
            B += N;

#ifdef GEMM_NEW_PACKING
            A6 = __riscv_vle32_v_f32m2(A0, M);
            A0 += M;
#else
            A6 = A_UNROLL2(M2, S, &A0, &A1, &A2, &A3, mask1, mask2);
#endif

            result0 = __riscv_vfmacc_vf_f32m2(result0, B0, A6, M);
            if (N >= 2) {
                result1 = __riscv_vfmacc_vf_f32m2(result1, B1, A6, M);
            }
            if (N >= 4) {
                result2 = __riscv_vfmacc_vf_f32m2(result2, B2, A6, M);
                result3 = __riscv_vfmacc_vf_f32m2(result3, B3, A6, M);
            }
            if (N == 8) {
                result4 = __riscv_vfmacc_vf_f32m2(result4, B4, A6, M);
                result5 = __riscv_vfmacc_vf_f32m2(result5, B5, A6, M);
                result6 = __riscv_vfmacc_vf_f32m2(result6, B6, A6, M);
                result7 = __riscv_vfmacc_vf_f32m2(result7, B7, A6, M);
            }
        }

        vfloat32m2_t c0, c1, c2, c3, c4, c5, c6, c7;
        c0 = __riscv_vle32_v_f32m2(&C[ldc * 0], M);
        if (N >= 2) {
            c1 = __riscv_vle32_v_f32m2(&C[ldc * 1], M);
        }
        if (N >= 4) {
            c2 = __riscv_vle32_v_f32m2(&C[ldc * 2], M);
            c3 = __riscv_vle32_v_f32m2(&C[ldc * 3], M);
        }

        c0 = __riscv_vfmacc_vf_f32m2(c0, alpha, result0, M);
        if (N >= 2) {
            c1 = __riscv_vfmacc_vf_f32m2(c1, alpha, result1, M);
        }
        if (N >= 4) {
            c2 = __riscv_vfmacc_vf_f32m2(c2, alpha, result2, M);
            c3 = __riscv_vfmacc_vf_f32m2(c3, alpha, result3, M);
        }

        __riscv_vse32_v_f32m2(&C[ldc * 0], c0, M);
        if (N >= 2) {
            __riscv_vse32_v_f32m2(&C[ldc * 1], c1, M);
        }
        if (N >= 4) {
            __riscv_vse32_v_f32m2(&C[ldc * 2], c2, M);
            __riscv_vse32_v_f32m2(&C[ldc * 3], c3, M);
        }

        if (N == 8) {
            c4 = __riscv_vle32_v_f32m2(&C[ldc * 4], M);
            c5 = __riscv_vle32_v_f32m2(&C[ldc * 5], M);
            c6 = __riscv_vle32_v_f32m2(&C[ldc * 6], M);
            c7 = __riscv_vle32_v_f32m2(&C[ldc * 7], M);

            c4 = __riscv_vfmacc_vf_f32m2(c4, alpha, result4, M);
            c5 = __riscv_vfmacc_vf_f32m2(c5, alpha, result5, M);
            c6 = __riscv_vfmacc_vf_f32m2(c6, alpha, result6, M);
            c7 = __riscv_vfmacc_vf_f32m2(c7, alpha, result7, M);

            __riscv_vse32_v_f32m2(&C[ldc * 4], c4, M);
            __riscv_vse32_v_f32m2(&C[ldc * 5], c5, M);
            __riscv_vse32_v_f32m2(&C[ldc * 6], c6, M);
            __riscv_vse32_v_f32m2(&C[ldc * 7], c7, M);
        }
    } else {
#ifdef GEMM_NEW_PACKING
        vfloat32m1_t A4 = __riscv_vle32_v_f32m1(A0, M);
        A0 += M;
#else
        vfloat32m1_t A4 = A_UNROLL(M, S, &A1, &A2, &A3, mask1, mask2);
#endif

        vfloat32m1_t result0, result1, result2, result3, result4, result5, result6, result7;
        result0 = __riscv_vfmul_vf_f32m1(A4, B0, M);
        if (N >= 2) {
            result1 = __riscv_vfmul_vf_f32m1(A4, B1, M);
        }
        if (N >= 4) {
            result2 = __riscv_vfmul_vf_f32m1(A4, B2, M);
            result3 = __riscv_vfmul_vf_f32m1(A4, B3, M);
        }
        if (N == 8) {
            result4 = __riscv_vfmul_vf_f32m1(A4, B4, M);
            result5 = __riscv_vfmul_vf_f32m1(A4, B5, M);
            result6 = __riscv_vfmul_vf_f32m1(A4, B6, M);
            result7 = __riscv_vfmul_vf_f32m1(A4, B7, M);
        }

        for (BLASLONG k = 1; k < K; k++) {
            B0 = B[0];
            if (N >= 2) {
                B1 = B[1];
            }
            if (N >= 4) {
                B2 = B[2];
                B3 = B[3];
            }
            if (N == 8) {
                B4 = B[4];
                B5 = B[5];
                B6 = B[6];
                B7 = B[7];
            }
            B += N;

#ifdef GEMM_NEW_PACKING
            A4 = __riscv_vle32_v_f32m1(A0, M);
            A0 += M;
#else
            A4 = A_UNROLL(M, S, &A1, &A2, &A3, mask1, mask2);
#endif

            result0 = __riscv_vfmacc_vf_f32m1(result0, B0, A4, M);
            if (N >= 2) {
                result1 = __riscv_vfmacc_vf_f32m1(result1, B1, A4, M);
            }
            if (N >= 4) {
                result2 = __riscv_vfmacc_vf_f32m1(result2, B2, A4, M);
                result3 = __riscv_vfmacc_vf_f32m1(result3, B3, A4, M);
            }
            if (N == 8) {
                result4 = __riscv_vfmacc_vf_f32m1(result4, B4, A4, M);
                result5 = __riscv_vfmacc_vf_f32m1(result5, B5, A4, M);
                result6 = __riscv_vfmacc_vf_f32m1(result6, B6, A4, M);
                result7 = __riscv_vfmacc_vf_f32m1(result7, B7, A4, M);
            }
        }

        vfloat32m1_t c0, c1, c2, c3, c4, c5, c6, c7;
        c0 = __riscv_vle32_v_f32m1(&C[ldc * 0], M);
        if (N >= 2) {
            c1 = __riscv_vle32_v_f32m1(&C[ldc * 1], M);
        }
        if (N >= 4) {
            c2 = __riscv_vle32_v_f32m1(&C[ldc * 2], M);
            c3 = __riscv_vle32_v_f32m1(&C[ldc * 3], M);
        }
        if (N == 8) {
            c4 = __riscv_vle32_v_f32m1(&C[ldc * 4], M);
            c5 = __riscv_vle32_v_f32m1(&C[ldc * 5], M);
            c6 = __riscv_vle32_v_f32m1(&C[ldc * 6], M);
            c7 = __riscv_vle32_v_f32m1(&C[ldc * 7], M);
        }

        c0 = __riscv_vfmacc_vf_f32m1(c0, alpha, result0, M);
        if (N >= 2) {
            c1 = __riscv_vfmacc_vf_f32m1(c1, alpha, result1, M);
        }
        if (N >= 4) {
            c2 = __riscv_vfmacc_vf_f32m1(c2, alpha, result2, M);
            c3 = __riscv_vfmacc_vf_f32m1(c3, alpha, result3, M);
        }
        if (N == 8) {
            c4 = __riscv_vfmacc_vf_f32m1(c4, alpha, result4, M);
            c5 = __riscv_vfmacc_vf_f32m1(c5, alpha, result5, M);
            c6 = __riscv_vfmacc_vf_f32m1(c6, alpha, result6, M);
            c7 = __riscv_vfmacc_vf_f32m1(c7, alpha, result7, M);
        }

        __riscv_vse32_v_f32m1(&C[ldc * 0], c0, M);
        if (N >= 2) {
            __riscv_vse32_v_f32m1(&C[ldc * 1], c1, M);
        }
        if (N >= 4) {
            __riscv_vse32_v_f32m1(&C[ldc * 2], c2, M);
            __riscv_vse32_v_f32m1(&C[ldc * 3], c3, M);
        }
        if (N == 8) {
            __riscv_vse32_v_f32m1(&C[ldc * 4], c4, M);
            __riscv_vse32_v_f32m1(&C[ldc * 5], c5, M);
            __riscv_vse32_v_f32m1(&C[ldc * 6], c6, M);
            __riscv_vse32_v_f32m1(&C[ldc * 7], c7, M);
        }
    }
}

static void FORCEINLINE M_TAIL(BLASLONG K, const BLASLONG M, const BLASLONG N, const BLASLONG M_BITS, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc)
{
#ifndef GEMM_NEW_PACKING
    vbool32_t mask1, mask2;
    BLASLONG M2 = M & 7;
    FLOAT *A1, *A2, *A3;

    if (M_BITS <= 1) {
        mask1 = __riscv_vreinterpret_v_u8m1_b32(__riscv_vundefined_u8m1());
        A1 = A + ((M > 8) ? (K * 8) : 0);
        M_TAIL_ONE(K, M, N, 1, alpha, A, A1, A1, A1, B, C, ldc, mask1, mask1);
        return;
    } else if (M_BITS == 2) {
        if (M2 > 5) {
            A2 = A + (K * 4) - 4;
            mask1 = __riscv_vreinterpret_v_u8m1_b32(__riscv_vmv_v_x_u8m1(0x30, M2));
        } else if (M2 == 5) {
            A2 = A + (K * 4) - 4;
            mask1 = __riscv_vreinterpret_v_u8m1_b32(__riscv_vmv_v_x_u8m1(0x10, M2));
        } else {  // 3
            A2 = A + (K * 2) - 2;
            mask1 = __riscv_vreinterpret_v_u8m1_b32(__riscv_vmv_v_x_u8m1(0x04, M2));
        }
    } else {
        A2 = A + (K * 4) - 4;
        A3 = A + (K * 6) - 6;
        mask1 = __riscv_vreinterpret_v_u8m1_b32(__riscv_vmv_v_x_u8m1(0x30, M2));
        mask2 = __riscv_vreinterpret_v_u8m1_b32(__riscv_vmv_v_x_u8m1(0x40, M2));
    }

    if (M > 8) {
        A1 = A + (K * 8);
        A2 += (K * 8);
        if (M_BITS == 2) {
            if (M > 13) {
                M_TAIL_ONE(K, 14, N, 2, alpha, A, A1, A2, A2, B, C, ldc, mask1, mask1);
            } else if (M == 13) {
                M_TAIL_ONE(K, 13, N, 2, alpha, A, A1, A2, A2, B, C, ldc, mask1, mask1);
            } else {
                M_TAIL_ONE(K, 11, N, 2, alpha, A, A1, A2, A2, B, C, ldc, mask1, mask1);
            }
        } else {
            A3 += (K * 8);
            M_TAIL_ONE(K, 15, N, 3, alpha, A, A1, A2, A3, B, C, ldc, mask1, mask2);
        }
    } else {
        A1 = A;
        if (M_BITS == 2) {
            if (M > 5) {
                M_TAIL_ONE(K, 6, N, 2, alpha, A, A1, A2, A2, B, C, ldc, mask1, mask1);
            } else if (M == 5) {
                M_TAIL_ONE(K, 5, N, 2, alpha, A, A1, A2, A2, B, C, ldc, mask1, mask1);
            } else {
                M_TAIL_ONE(K, 3, N, 2, alpha, A, A1, A2, A2, B, C, ldc, mask1, mask1);
            }
        } else {
            M_TAIL_ONE(K, 7, N, 3, alpha, A, A1, A2, A3, B, C, ldc, mask1, mask2);
        }
    }
#else
    M_TAIL_ONE(K, M, N, alpha, A, B, C, ldc);
#endif
}
#endif

int CNAME(BLASLONG M, BLASLONG N, BLASLONG K, FLOAT alpha, FLOAT* A, FLOAT* B, FLOAT* C, BLASLONG ldc)
{
    BLASLONG gvl = 0;
    BLASLONG m_top = 0;
    BLASLONG n_top = 0;
#ifdef GEMM_RIGHT_EDGE
    const BLASLONG m_edge = M & 15;
#ifdef GEMM_NEW_PACKING
    const BLASLONG m_bits = 0;
#else
    const BLASLONG m_bits = __builtin_popcount(M & 7);
#endif
#endif


    // -- MAIN PASS

    for (BLASLONG j=0; j<N/8; j+=1) {
        m_top = 0;
        BLASLONG gvl = __riscv_vsetvl_e32m1(8);


        for (BLASLONG i=0; i<M/16; i+=1) {
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            float B4 = B[bi+4];
            float B5 = B[bi+5];
            float B6 = B[bi+6];
            float B7 = B[bi+7];
            bi += 8;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            vfloat32m1_t A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
            ai += 16;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A1, B0, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A1, B1, gvl);
            vfloat32m1_t result4 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result5 = __riscv_vfmul_vf_f32m1( A1, B2, gvl);
            vfloat32m1_t result6 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);
            vfloat32m1_t result7 = __riscv_vfmul_vf_f32m1( A1, B3, gvl);
            vfloat32m1_t result8 = __riscv_vfmul_vf_f32m1( A0, B4, gvl);
            vfloat32m1_t result9 = __riscv_vfmul_vf_f32m1( A1, B4, gvl);
            vfloat32m1_t result10 = __riscv_vfmul_vf_f32m1( A0, B5, gvl);
            vfloat32m1_t result11 = __riscv_vfmul_vf_f32m1( A1, B5, gvl);
            vfloat32m1_t result12 = __riscv_vfmul_vf_f32m1( A0, B6, gvl);
            vfloat32m1_t result13 = __riscv_vfmul_vf_f32m1( A1, B6, gvl);
            vfloat32m1_t result14 = __riscv_vfmul_vf_f32m1( A0, B7, gvl);
            vfloat32m1_t result15 = __riscv_vfmul_vf_f32m1( A1, B7, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                B4 = B[bi+4];
                B5 = B[bi+5];
                B6 = B[bi+6];
                B7 = B[bi+7];
                bi += 8;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B0, A1, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B1, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B1, A1, gvl);
                result4 = __riscv_vfmacc_vf_f32m1( result4, B2, A0, gvl);
                result5 = __riscv_vfmacc_vf_f32m1( result5, B2, A1, gvl);
                result6 = __riscv_vfmacc_vf_f32m1( result6, B3, A0, gvl);
                result7 = __riscv_vfmacc_vf_f32m1( result7, B3, A1, gvl);
                result8 = __riscv_vfmacc_vf_f32m1( result8, B4, A0, gvl);
                result9 = __riscv_vfmacc_vf_f32m1( result9, B4, A1, gvl);
                result10 = __riscv_vfmacc_vf_f32m1( result10, B5, A0, gvl);
                result11 = __riscv_vfmacc_vf_f32m1( result11, B5, A1, gvl);
                result12 = __riscv_vfmacc_vf_f32m1( result12, B6, A0, gvl);
                result13 = __riscv_vfmacc_vf_f32m1( result13, B6, A1, gvl);
                result14 = __riscv_vfmacc_vf_f32m1( result14, B7, A0, gvl);
                result15 = __riscv_vfmacc_vf_f32m1( result15, B7, A1, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c4 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c5 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c6 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c7 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c8 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c9 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c10 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c11 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c12 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c13 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c14 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c15 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );
            c4 = __riscv_vfmacc_vf_f32m1( c4, alpha, result4, gvl );
            c5 = __riscv_vfmacc_vf_f32m1( c5, alpha, result5, gvl );
            c6 = __riscv_vfmacc_vf_f32m1( c6, alpha, result6, gvl );
            c7 = __riscv_vfmacc_vf_f32m1( c7, alpha, result7, gvl );
            c8 = __riscv_vfmacc_vf_f32m1( c8, alpha, result8, gvl );
            c9 = __riscv_vfmacc_vf_f32m1( c9, alpha, result9, gvl );
            c10 = __riscv_vfmacc_vf_f32m1( c10, alpha, result10, gvl );
            c11 = __riscv_vfmacc_vf_f32m1( c11, alpha, result11, gvl );
            c12 = __riscv_vfmacc_vf_f32m1( c12, alpha, result12, gvl );
            c13 = __riscv_vfmacc_vf_f32m1( c13, alpha, result13, gvl );
            c14 = __riscv_vfmacc_vf_f32m1( c14, alpha, result14, gvl );
            c15 = __riscv_vfmacc_vf_f32m1( c15, alpha, result15, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c4, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c5, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c6, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c7, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c8, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c9, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c10, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c11, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c12, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c13, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c14, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c15, gvl);
            m_top += 16;
        }



        // -- tails for main pass

#ifndef GEMM_RIGHT_EDGE
        if( M & 8 ) {
            gvl = __riscv_vsetvl_e32m1(8);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            float B4 = B[bi+4];
            float B5 = B[bi+5];
            float B6 = B[bi+6];
            float B7 = B[bi+7];
            bi += 8;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 8;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);
            vfloat32m1_t result4 = __riscv_vfmul_vf_f32m1( A0, B4, gvl);
            vfloat32m1_t result5 = __riscv_vfmul_vf_f32m1( A0, B5, gvl);
            vfloat32m1_t result6 = __riscv_vfmul_vf_f32m1( A0, B6, gvl);
            vfloat32m1_t result7 = __riscv_vfmul_vf_f32m1( A0, B7, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                B4 = B[bi+4];
                B5 = B[bi+5];
                B6 = B[bi+6];
                B7 = B[bi+7];
                bi += 8;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 8;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B2, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B3, A0, gvl);
                result4 = __riscv_vfmacc_vf_f32m1( result4, B4, A0, gvl);
                result5 = __riscv_vfmacc_vf_f32m1( result5, B5, A0, gvl);
                result6 = __riscv_vfmacc_vf_f32m1( result6, B6, A0, gvl);
                result7 = __riscv_vfmacc_vf_f32m1( result7, B7, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c4 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c5 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c6 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c7 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );
            c4 = __riscv_vfmacc_vf_f32m1( c4, alpha, result4, gvl );
            c5 = __riscv_vfmacc_vf_f32m1( c5, alpha, result5, gvl );
            c6 = __riscv_vfmacc_vf_f32m1( c6, alpha, result6, gvl );
            c7 = __riscv_vfmacc_vf_f32m1( c7, alpha, result7, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c4, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c5, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c6, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c7, gvl);
            m_top += 8;
        }


        if( M & 4 ) {
            gvl = __riscv_vsetvl_e32m1(4);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            float B4 = B[bi+4];
            float B5 = B[bi+5];
            float B6 = B[bi+6];
            float B7 = B[bi+7];
            bi += 8;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 4;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);
            vfloat32m1_t result4 = __riscv_vfmul_vf_f32m1( A0, B4, gvl);
            vfloat32m1_t result5 = __riscv_vfmul_vf_f32m1( A0, B5, gvl);
            vfloat32m1_t result6 = __riscv_vfmul_vf_f32m1( A0, B6, gvl);
            vfloat32m1_t result7 = __riscv_vfmul_vf_f32m1( A0, B7, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                B4 = B[bi+4];
                B5 = B[bi+5];
                B6 = B[bi+6];
                B7 = B[bi+7];
                bi += 8;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 4;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B2, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B3, A0, gvl);
                result4 = __riscv_vfmacc_vf_f32m1( result4, B4, A0, gvl);
                result5 = __riscv_vfmacc_vf_f32m1( result5, B5, A0, gvl);
                result6 = __riscv_vfmacc_vf_f32m1( result6, B6, A0, gvl);
                result7 = __riscv_vfmacc_vf_f32m1( result7, B7, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c4 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c5 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c6 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c7 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );
            c4 = __riscv_vfmacc_vf_f32m1( c4, alpha, result4, gvl );
            c5 = __riscv_vfmacc_vf_f32m1( c5, alpha, result5, gvl );
            c6 = __riscv_vfmacc_vf_f32m1( c6, alpha, result6, gvl );
            c7 = __riscv_vfmacc_vf_f32m1( c7, alpha, result7, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c4, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c5, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c6, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c7, gvl);
            m_top += 4;
        }


        if( M & 2 ) {
            float result0 = 0;
            float result1 = 0;
            float result2 = 0;
            float result3 = 0;
            float result4 = 0;
            float result5 = 0;
            float result6 = 0;
            float result7 = 0;
            float result8 = 0;
            float result9 = 0;
            float result10 = 0;
            float result11 = 0;
            float result12 = 0;
            float result13 = 0;
            float result14 = 0;
            float result15 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+1]*B[bi+0];
                result2+=A[ai+0]*B[bi+1];
                result3+=A[ai+1]*B[bi+1];
                result4+=A[ai+0]*B[bi+2];
                result5+=A[ai+1]*B[bi+2];
                result6+=A[ai+0]*B[bi+3];
                result7+=A[ai+1]*B[bi+3];
                result8+=A[ai+0]*B[bi+4];
                result9+=A[ai+1]*B[bi+4];
                result10+=A[ai+0]*B[bi+5];
                result11+=A[ai+1]*B[bi+5];
                result12+=A[ai+0]*B[bi+6];
                result13+=A[ai+1]*B[bi+6];
                result14+=A[ai+0]*B[bi+7];
                result15+=A[ai+1]*B[bi+7];
                ai+=2;
                bi+=8;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+0*ldc+1] += alpha * result1;
            C[ci+1*ldc+0] += alpha * result2;
            C[ci+1*ldc+1] += alpha * result3;
            C[ci+2*ldc+0] += alpha * result4;
            C[ci+2*ldc+1] += alpha * result5;
            C[ci+3*ldc+0] += alpha * result6;
            C[ci+3*ldc+1] += alpha * result7;
            C[ci+4*ldc+0] += alpha * result8;
            C[ci+4*ldc+1] += alpha * result9;
            C[ci+5*ldc+0] += alpha * result10;
            C[ci+5*ldc+1] += alpha * result11;
            C[ci+6*ldc+0] += alpha * result12;
            C[ci+6*ldc+1] += alpha * result13;
            C[ci+7*ldc+0] += alpha * result14;
            C[ci+7*ldc+1] += alpha * result15;
            m_top+=2;
        }


        if( M & 1 ) {
            float result0 = 0;
            float result1 = 0;
            float result2 = 0;
            float result3 = 0;
            float result4 = 0;
            float result5 = 0;
            float result6 = 0;
            float result7 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+0]*B[bi+1];
                result2+=A[ai+0]*B[bi+2];
                result3+=A[ai+0]*B[bi+3];
                result4+=A[ai+0]*B[bi+4];
                result5+=A[ai+0]*B[bi+5];
                result6+=A[ai+0]*B[bi+6];
                result7+=A[ai+0]*B[bi+7];
                ai+=1;
                bi+=8;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+1*ldc+0] += alpha * result1;
            C[ci+2*ldc+0] += alpha * result2;
            C[ci+3*ldc+0] += alpha * result3;
            C[ci+4*ldc+0] += alpha * result4;
            C[ci+5*ldc+0] += alpha * result5;
            C[ci+6*ldc+0] += alpha * result6;
            C[ci+7*ldc+0] += alpha * result7;
            m_top+=1;
        }
#else
        if (m_edge) {
            M_TAIL(K, m_edge, 8, m_bits, alpha, &A[m_top*K], &B[n_top*K], &C[n_top*ldc+m_top], ldc);
        }
#endif

        n_top += 8;
    }



    // -- tails for N=4

    if( N & 4 ) {
        gvl = __riscv_vsetvl_e32m1(8);
        m_top = 0;

        for (BLASLONG i=0; i<M/16; i+=1) {
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            bi += 4;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            vfloat32m1_t A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
            ai += 16;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A1, B0, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A1, B1, gvl);
            vfloat32m1_t result4 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result5 = __riscv_vfmul_vf_f32m1( A1, B2, gvl);
            vfloat32m1_t result6 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);
            vfloat32m1_t result7 = __riscv_vfmul_vf_f32m1( A1, B3, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                bi += 4;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B0, A1, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B1, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B1, A1, gvl);
                result4 = __riscv_vfmacc_vf_f32m1( result4, B2, A0, gvl);
                result5 = __riscv_vfmacc_vf_f32m1( result5, B2, A1, gvl);
                result6 = __riscv_vfmacc_vf_f32m1( result6, B3, A0, gvl);
                result7 = __riscv_vfmacc_vf_f32m1( result7, B3, A1, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c4 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c5 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c6 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c7 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );
            c4 = __riscv_vfmacc_vf_f32m1( c4, alpha, result4, gvl );
            c5 = __riscv_vfmacc_vf_f32m1( c5, alpha, result5, gvl );
            c6 = __riscv_vfmacc_vf_f32m1( c6, alpha, result6, gvl );
            c7 = __riscv_vfmacc_vf_f32m1( c7, alpha, result7, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c4, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c5, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c6, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c7, gvl);
            m_top += 16;
        }


        if( M & 8 ) {
            gvl = __riscv_vsetvl_e32m1(8);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            bi += 4;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 8;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                bi += 4;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 8;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B2, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B3, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl);
            m_top += 8;
        }


        if( M & 4 ) {
            gvl = __riscv_vsetvl_e32m1(4);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            float B2 = B[bi+2];
            float B3 = B[bi+3];
            bi += 4;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 4;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B2, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A0, B3, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                B2 = B[bi+2];
                B3 = B[bi+3];
                bi += 4;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 4;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B2, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B3, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl);
            m_top += 4;
        }


        if( M & 2 ) {
            float result0 = 0;
            float result1 = 0;
            float result2 = 0;
            float result3 = 0;
            float result4 = 0;
            float result5 = 0;
            float result6 = 0;
            float result7 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+1]*B[bi+0];
                result2+=A[ai+0]*B[bi+1];
                result3+=A[ai+1]*B[bi+1];
                result4+=A[ai+0]*B[bi+2];
                result5+=A[ai+1]*B[bi+2];
                result6+=A[ai+0]*B[bi+3];
                result7+=A[ai+1]*B[bi+3];
                ai+=2;
                bi+=4;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+0*ldc+1] += alpha * result1;
            C[ci+1*ldc+0] += alpha * result2;
            C[ci+1*ldc+1] += alpha * result3;
            C[ci+2*ldc+0] += alpha * result4;
            C[ci+2*ldc+1] += alpha * result5;
            C[ci+3*ldc+0] += alpha * result6;
            C[ci+3*ldc+1] += alpha * result7;
            m_top+=2;
        }


        if( M & 1 ) {
            float result0 = 0;
            float result1 = 0;
            float result2 = 0;
            float result3 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+0]*B[bi+1];
                result2+=A[ai+0]*B[bi+2];
                result3+=A[ai+0]*B[bi+3];
                ai+=1;
                bi+=4;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+1*ldc+0] += alpha * result1;
            C[ci+2*ldc+0] += alpha * result2;
            C[ci+3*ldc+0] += alpha * result3;
            m_top+=1;
        }

        n_top += 4;
    }



    // -- tails for N=2

    if( N & 2 ) {
        gvl = __riscv_vsetvl_e32m1(8);
        m_top = 0;

        for (BLASLONG i=0; i<M/16; i+=1) {
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            bi += 2;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            vfloat32m1_t A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
            ai += 16;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A1, B0, gvl);
            vfloat32m1_t result2 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);
            vfloat32m1_t result3 = __riscv_vfmul_vf_f32m1( A1, B1, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                bi += 2;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B0, A1, gvl);
                result2 = __riscv_vfmacc_vf_f32m1( result2, B1, A0, gvl);
                result3 = __riscv_vfmacc_vf_f32m1( result3, B1, A1, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*1;
            vfloat32m1_t c2 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c3 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );
            c2 = __riscv_vfmacc_vf_f32m1( c2, alpha, result2, gvl );
            c3 = __riscv_vfmacc_vf_f32m1( c3, alpha, result3, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl); ci += ldc-gvl*1;
            __riscv_vse32_v_f32m1( &C[ci], c2, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c3, gvl);
            m_top += 16;
        }


        if( M & 8 ) {
            gvl = __riscv_vsetvl_e32m1(8);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            bi += 2;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 8;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                bi += 2;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 8;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl);
            m_top += 8;
        }


        if( M & 4 ) {
            gvl = __riscv_vsetvl_e32m1(4);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            float B1 = B[bi+1];
            bi += 2;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 4;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A0, B1, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                B1 = B[bi+1];
                bi += 2;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 4;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B1, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += ldc-gvl*0;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += ldc-gvl*0;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl);
            m_top += 4;
        }


        if( M & 2 ) {
            float result0 = 0;
            float result1 = 0;
            float result2 = 0;
            float result3 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+1]*B[bi+0];
                result2+=A[ai+0]*B[bi+1];
                result3+=A[ai+1]*B[bi+1];
                ai+=2;
                bi+=2;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+0*ldc+1] += alpha * result1;
            C[ci+1*ldc+0] += alpha * result2;
            C[ci+1*ldc+1] += alpha * result3;
            m_top+=2;
        }


        if( M & 1 ) {
            float result0 = 0;
            float result1 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+0]*B[bi+1];
                ai+=1;
                bi+=2;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+1*ldc+0] += alpha * result1;
            m_top+=1;
        }

        n_top += 2;
    }



    // -- tails for N=1

    if( N & 1 ) {
        gvl = __riscv_vsetvl_e32m1(8);
        m_top = 0;

        for (BLASLONG i=0; i<M/16; i+=1) {
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            bi += 1;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            vfloat32m1_t A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
            ai += 16;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);
            vfloat32m1_t result1 = __riscv_vfmul_vf_f32m1( A1, B0, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                bi += 1;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                A1 = __riscv_vle32_v_f32m1( &A[ai+1*gvl], gvl );
                ai += 16;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
                result1 = __riscv_vfmacc_vf_f32m1( result1, B0, A1, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl); ci += gvl;
            vfloat32m1_t c1 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );
            c1 = __riscv_vfmacc_vf_f32m1( c1, alpha, result1, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl); ci += gvl;
            __riscv_vse32_v_f32m1( &C[ci], c1, gvl);
            m_top += 16;
        }


        if( M & 8 ) {
            gvl = __riscv_vsetvl_e32m1(8);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            bi += 1;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 8;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                bi += 1;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 8;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl);
            m_top += 8;
        }


        if( M & 4 ) {
            gvl = __riscv_vsetvl_e32m1(4);

            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;
            float B0 = B[bi+0];
            bi += 1;

            vfloat32m1_t A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
            ai += 4;

            vfloat32m1_t result0 = __riscv_vfmul_vf_f32m1( A0, B0, gvl);

            for(BLASLONG k=1; k<K; k++) {
                B0 = B[bi+0];
                bi += 1;

                A0 = __riscv_vle32_v_f32m1( &A[ai+0*gvl], gvl );
                ai += 4;

                result0 = __riscv_vfmacc_vf_f32m1( result0, B0, A0, gvl);
            }


            BLASLONG ci=n_top*ldc+m_top;

            vfloat32m1_t c0 = __riscv_vle32_v_f32m1( &C[ci], gvl);
            c0 = __riscv_vfmacc_vf_f32m1( c0, alpha, result0, gvl );

            ci=n_top*ldc+m_top;

            __riscv_vse32_v_f32m1( &C[ci], c0, gvl);
            m_top += 4;
        }


        if( M & 2 ) {
            float result0 = 0;
            float result1 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                result1+=A[ai+1]*B[bi+0];
                ai+=2;
                bi+=1;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            C[ci+0*ldc+1] += alpha * result1;
            m_top+=2;
        }


        if( M & 1 ) {
            float result0 = 0;
            BLASLONG ai=m_top*K;
            BLASLONG bi=n_top*K;

            for(BLASLONG k=0; k<K; k++) {
                result0+=A[ai+0]*B[bi+0];
                ai+=1;
                bi+=1;
            }

            BLASLONG ci=n_top*ldc+m_top;
            C[ci+0*ldc+0] += alpha * result0;
            m_top+=1;
        }

        n_top += 1;
    }

    return 0;
}

